const express = require('express')
const app = express()
const path = require('path')
app.use(express.static(__dirname))
app.use('/dist', express.static(path.resolve(__dirname, '../../dist')))
app.listen(3000)